version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ~/lpi-monitoring/grafana-storage:/var/lib/grafana
      - ~/lpi-monitoring/dashboards_grafana/grafana:/etc/grafana/provisioning/dashboards
    restart: always

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ~/lpi-monitoring/prometheus-storage:/prometheus
      - ~/lpi-monitoring/configs/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    restart: always

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - ~/lpi-monitoring/loki-storage:/loki
      - ~/lpi-monitoring/configs/loki:/etc/loki
      - ~/lpi-monitoring/loki-wal:/wal
    command: -config.file=/etc/loki/loki-config.yaml
    restart: always

  promtail:
    image: grafana/promtail
    ports:
      - "1514:514"
      - "1514:514/udp"
    volumes:
      - ~/lpi-monitoring/configs/promtail:/etc/promtail
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yaml
    restart: always

  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - ~/lpi-monitoring/influxdb-storage:/var/lib/influxdb
    restart: always

  fluentd:
    image: grafana/fluent-plugin-loki:latest
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - ~/lpi-monitoring/configs/fluentd:/fluentd/etc
      - /var/log/pfsense:/var/log/pfsense
    command: fluentd -c /fluentd/etc/fluent.conf --use-v1-config
    restart: always
