version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ~/lpi-monitoring/grafana-storage:/var/lib/grafana
      - ~/lpi-monitoring/configs/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ~/lpi-monitoring/configs/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ~/lpi-monitoring/grafana-storage/dashboards:/var/lib/grafana/dashboards
    restart: always
