version: '3'

services:
  fluentd:
    image: grafana/fluent-plugin-loki:latest
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - ~/LPI/configs/fluentd:/fluentd/etc
      - /var/log/pfsense:/var/log/pfsense
    command: fluentd -c /fluentd/etc/fluent.conf --use-v1-config
    restart: always
