version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ${HOME}/lpi-monitoring/influxdb-storage:/var/lib/influxdb:rw
    environment:
      - INFLUXDB_DB=${INFLUXDB_DB:-lpi}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-adminadmin}
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_HTTP_HTTPS_ENABLED=true
      - INFLUXDB_HTTP_BIND_ADDRESS=:8086
      - INFLUXDB_REPORTING_DISABLED=true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    user: "influxdb:influxdb"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    networks:
      - lpi_network

networks:
  lpi_network:
    driver: bridge
