version: '3.8'

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - ${HOME}/lpi-monitoring/loki-storage:/loki:rw
      - ${HOME}/lpi-monitoring/configs/loki:/etc/loki:ro
      - ${HOME}/lpi-monitoring/loki-wal:/wal:rw
    command: -config.file=/etc/loki/loki-config.yaml
    environment:
      - LOKI_PATH=/loki
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    user: "10001:10001"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    networks:
      - lpi_network

networks:
  lpi_network:
    driver: bridge
