version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ${HOME}/lpi-monitoring/grafana-storage:/var/lib/grafana:rw
      - ${HOME}/lpi-monitoring/configs/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ${HOME}/lpi-monitoring/configs/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ${HOME}/lpi-monitoring/grafana-storage/dashboards:/var/lib/grafana/dashboards:rw
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SECURITY_ALLOW_EMBEDDING=false
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_SECURITY_DISABLE_GRAVATAR=true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    user: "472:472"
    security_opt:
      - no-new-privileges:true
    read_only: true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    networks:
      - lpi_network

networks:
  lpi_network:
    driver: bridge
