version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ~/LPI/grafana-storage:/var/lib/grafana
      - ~/LPI/dashboards_grafana/grafana:/etc/grafana/provisioning/dashboards

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ~/LPI/prometheus-storage:/prometheus
      - ~/LPI/configs/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'

  loki:
    image: grafana/loki
    ports:
      - "3100:3100"
    volumes:
      - ~/LPI/loki-storage:/loki
      - ~/LPI/configs/loki:/etc/loki
      - ~/LPI/loki-wal:/wal
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail
    ports:
      - "1514:514"
      - "1514:514/udp"
    volumes:
      - ~/LPI/configs/promtail:/etc/promtail
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yaml

  influxdb:
    image: influxdb
    ports:
      - 8086:8086
    volumes:
      - ~/LPI/influxdb-storage:/var/lib/influxdb

  fluentd:
    image: grafana/fluent-plugin-loki:latest
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - ~/LPI/configs/fluentd:/fluentd/etc
      - /var/log/pfsense:/var/log/pfsense
    command: fluentd -c /fluentd/etc/fluent.conf --use-v1-config
