version: '3.8'

services:
  promtail:
    image: grafana/promtail:latest
    ports:
      - "1514:1514"
      - "1514:1514/udp"
    volumes:
      - ${HOME}/lpi-monitoring/configs/promtail:/etc/promtail:ro
      - /var/log:/var/log:ro
    command: -config.file=/etc/promtail/promtail-config.yaml
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    user: "10001:10001"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID
    networks:
      - lpi_network

networks:
  lpi_network:
    driver: bridge
