version: '3'

services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ~/LPI/grafana-storage:/var/lib/grafana
      - ~/LPI/dashboards_grafana/grafana:/etc/grafana/provisioning/dashboards
    restart: always
