version: '3'

services:
  promtail:
    image: grafana/promtail
    ports:
      - "1514:514"
      - "1514:514/udp"
    volumes:
      - ~/lpi-monitoring/configs/promtail:/etc/promtail
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail-config.yaml
    restart: always
