version: '3'

services:
  influxdb:
    image: influxdb:latest
    ports:
      - 8086:8086
    volumes:
      - ~/lpi-monitoring/influxdb-storage:/var/lib/influxdb:rw
    environment:
      - INFLUXDB_DB=lpi
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=adminadmin
      - INFLUXDB_HTTP_AUTH_ENABLED=true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
