version: '3'

services:
  fluentd:
    image: grafana/fluent-plugin-loki:latest
    ports:
      - 24224:24224
      - 24224:24224/udp
    volumes:
      - ~/lpi-monitoring/configs/fluentd:/fluentd/etc:ro
      - /var/log/pfsense:/var/log/pfsense:rw
      - /path/to/Archives_Logs/fluentd_logs_archives:/fluentd/logs:rw
    environment:
      - FLUENT_UID=0 # Assure les permissions root pour éviter les problèmes d'accès
    command: fluentd -c /fluentd/etc/fluent.conf --use-v1-config
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
